# config/schema/entity.view.display.component.default.yml
langcode: en
status: true
dependencies:
  module:
    - component
id: component.default
targetEntityType: component
display:
  type: component_default
  label: Default
  weight: 0
  status: true
  layout:
    id: two_column
    label: Two column
    category: layout
    regions:
      header:
        label: Header
        weight: 0
      body:
        label: Body
        weight: 1
        columns:
          - { width: 50%, label: 'Column 1' }
          - { width: 50%, label: 'Column 2' }
